# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Voting(object):
    def setupUi(self, Voting):
        Voting.setObjectName("Voting")
        Voting.resize(457, 357)
        self.centralwidget = QtWidgets.QWidget(parent=Voting)
        self.centralwidget.setObjectName("centralwidget")
        self.send_vote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send_vote.setGeometry(QtCore.QRect(50, 270, 81, 31))
        self.send_vote.setObjectName("send_vote")
        self.finish_vote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.finish_vote.setGeometry(QtCore.QRect(310, 270, 81, 31))
        self.finish_vote.setObjectName("finish_vote")
        self.first_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.first_name.setGeometry(QtCore.QRect(80, 70, 113, 20))
        self.first_name.setText("")
        self.first_name.setObjectName("first_name")
        self.Last_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Last_name.setGeometry(QtCore.QRect(80, 130, 113, 20))
        self.Last_name.setObjectName("Last_name")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(280, 70, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(280, 130, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 51, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 190, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 230, 261, 20))
        self.label_4.setObjectName("label_4")
        Voting.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Voting)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        Voting.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Voting)
        self.statusbar.setObjectName("statusbar")
        Voting.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Voting)
        QtCore.QMetaObject.connectSlotsByName(Voting)

    def retranslateUi(self, Voting):
        _translate = QtCore.QCoreApplication.translate
        Voting.setWindowTitle(_translate("Voting", "MainWindow"))
        self.send_vote.setText(_translate("Voting", "Send Vote"))
        self.finish_vote.setText(_translate("Voting", "Finish"))
        self.radioButton.setText(_translate("Voting", "John"))
        self.radioButton_2.setText(_translate("Voting", "Jane"))
        self.label.setText(_translate("Voting", "First name"))
        self.label_2.setText(_translate("Voting", "Last name"))
        self.label_3.setText(_translate("Voting", "Age"))
        self.label_4.setText(_translate("Voting", "Please enter your vote and information correctly"))
        self.menu.setTitle(_translate("Voting", "Voting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Voting = QtWidgets.QMainWindow()
    ui = Ui_Voting()
    ui.setupUi(Voting)
    Voting.show()
    sys.exit(app.exec())
